### ISSUE TITLE
Initial Anki -> Excel breaking

### ISSUE THREAD

**Issue by pcsc8ct** [BlueGreenMagick/sync-excel-with-anki#11]
This is quite possibly a very novice thing. Trying to set this add-on up today but I am getting an "invalidSearch" when trying to do an Anki -> Excel (not tried the other way yet). Any guidance appreciated - I am sure I am probably missing something dumb.

Debug info:
Anki 2.1.19 (3c8690ae) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
Traceback (most recent call last):
  File "C:\Users\HamerN\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\menu.py", line 45, in confirm_a2e_sync
    ExcelSync().a2e_sync()
  File "C:\Users\HamerN\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 281, in a2e_sync
    self.backup_then_sync(self._a2e_sync)
  File "C:\Users\HamerN\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 275, in backup_then_sync
    mw.unloadCollection(on_unload)
  File "aqt\main.py", line 450, in unloadCollection
  File "aqt\main.py", line 726, in closeAllWindows
  File "aqt\__init__.py", line 105, in closeAll
  File "aqt\main.py", line 448, in callback
  File "C:\Users\HamerN\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 273, in on_unload
    syncfunc()
  File "C:\Users\HamerN\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 641, in _a2e_sync
    raise e
  File "C:\Users\HamerN\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 512, in _a2e_sync
    card_ids = mw.col.findCards("tag:" + tag + "::*")
  File "lib\site-packages\anki\collection.py", line 700, in findCards
  File "lib\site-packages\anki\find.py", line 49, in findCards
Exception: invalidSearch

**Comment by BlueGreenMagick** [comment]
It is probably because one of your tag contains a special character. (i.e. ", ', *, etc) Can you try removing those special characters from all your tags and see if it works?

**Comment by pcsc8ct** [comment]
Yeah this was right. I found the rogue last night and the add-on is working
well now. Cheers!
