### ISSUE TITLE
problem with exel->anki

### ISSUE THREAD

**Issue by infinity2391** [BlueGreenMagick/sync-excel-with-anki#12]
hi! i've got a problem when i try to sync from exel to anki 

Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-11-26 23:24:26

Caught exception:
Traceback (most recent call last):
  File "aqt\taskman.py", line 87, in _on_closures_pending
  File "aqt\taskman.py", line 59, in <lambda>
  File "aqt\taskman.py", line 76, in wrapped_done
  File "aqt\sync.py", line 114, in on_future_done
  File "aqt\main.py", line 914, in on_collection_sync_finished
  File "aqt\main.py", line 542, in after_sync
  File "aqt\mediasync.py", line 129, in show_diag_until_finished
  File "aqt\main.py", line 539, in after_media_sync
  File "C:\Users\infin\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 273, in on_unload
    syncfunc()
  File "C:\Users\infin\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 483, in _e2a_sync
    raise e
  File "C:\Users\infin\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 361, in _e2a_sync
    raise Exception(msg)
Exception: ERROR: You need to set the directory for your excel files, in addon config.
Sync aborted

**Comment by BlueGreenMagick** [comment]
As written in the error log, you need to edit the addon config (Tools > Addon > select Anki Excel Sync > Config) and set `_directory` to the directory you stored your excel files in.
