### ISSUE TITLE
problem with Anki -> Excel

### ISSUE THREAD

**Issue by Jennie2021** [BlueGreenMagick/sync-excel-with-anki#18]
it is giving me this error message and I don't know how to grant access

Debug info:
Anki 2.1.42 (8eebfe18) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-22 16:34:47

Caught exception:
Traceback (most recent call last):
  File "aqt\taskman.py", line 88, in _on_closures_pending
  File "aqt\taskman.py", line 59, in <lambda>
  File "aqt\taskman.py", line 77, in wrapped_done
  File "aqt\sync.py", line 114, in on_future_done
  File "aqt\main.py", line 916, in on_collection_sync_finished
  File "aqt\main.py", line 531, in after_sync
  File "aqt\mediasync.py", line 124, in show_diag_until_finished
  File "aqt\main.py", line 528, in after_media_sync
  File "C:\Users\Dell\AppData\Roaming\Anki2\addons21\ankiExcelSync\ankiExcelSync\sync.py", line 253, in on_unload
    syncfunc()
  File "C:\Users\Dell\AppData\Roaming\Anki2\addons21\ankiExcelSync\ankiExcelSync\sync.py", line 564, in _a2e_sync
    raise e
  File "C:\Users\Dell\AppData\Roaming\Anki2\addons21\ankiExcelSync\ankiExcelSync\sync.py", line 549, in _a2e_sync
    os.remove(f)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Dell\\Documents\\_directory.xlsx'

**Comment by BlueGreenMagick** [comment]
If you can open the file, then Anki probably should have permission to open the file as well.

But I think you may have set the directory config wrong. Did you put your your anki notes in ‘C:\Users\Dell\Documents\_directory.xlsx’ file?

**Comment by Jennie2021** [comment]
@BlueGreenMagick Yeah 😅😅 should I not have done that?

**Comment by BlueGreenMagick** [comment]
Oh, in that case it should be OK? I thought it was a system file or something 😁 I’d warn you against using Documents directory though. If you have non-anki excel files in the directory they could get deleted.

For the permission error, do you perhaps have the excel file open in another window? Sometimes softwares lock the opened file so other softwares cannot edit it.

**Comment by Jennie2021** [comment]
@BlueGreenMagick oops 😅 it's fixed now thanks 👍🏽
