### ISSUE TITLE
Newbie here about Anki Excel Sync

### ISSUE THREAD

**Issue by Alexli0701** [BlueGreenMagick/sync-excel-with-anki#2]
Hi there, I just started using Anki today and wanted to export my glossary to excel. I installed the add-on but it showed error...
I don't know what I did wrong...Could you help me out?

Thank you in advance!!!

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.19 (3c8690ae) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Mac 10.15.3
Flags: frz=True ao=True sv=1
Add-ons possibly involved: Anki Excel Sync

Caught exception:
Traceback (most recent call last):
  File "/Users/alex1/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/menu.py", line 30, in confirm_e2a_sync
    ExcelSync().e2a_sync()
  File "/Users/alex1/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 246, in e2a_sync
    self.backup_then_sync(self._e2a_sync)
  File "/Users/alex1/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 243, in backup_then_sync
    mw.unloadCollection(on_unload)
  File "aqt/main.py", line 450, in unloadCollection
  File "aqt/main.py", line 726, in closeAllWindows
  File "aqt/__init__.py", line 105, in closeAll
  File "aqt/main.py", line 448, in callback
  File "/Users/alex1/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 242, in on_unload
    syncfunc()
  File "/Users/alex1/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 419, in _e2a_sync
    raise e
  File "/Users/alex1/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 324, in _e2a_sync
    raise Exception(msg)
Exception: ERROR: You need to set the directory for your excel files, in addon config.
Sync aborted

**Comment by BlueGreenMagick** [comment]
As written in the last line, you need to set the directory that your excel files are(will be) stored in.

Go to Tools > Addons > click Anki Excel Sync > click config, Then set '_directory' to the full directory path that you want the excel files to be in. Note that when you run 'Anki -> Excel' sync, all other excel files stored in the directory will be deleted, so set it to an empty directory!

You should also start with 'Anki to Excel' sync. The addon requires the excel files to be properly formatted with the list of note types and fields in the beginning of Excel. Which is hard to do manually. Much easier to edit an existing formatted excel file.

**Comment by BlueGreenMagick** [comment]
You can see here how an excel file needs to be formatted for the addon to be able to import in:
https://github.com/BlueGreenMagick/sync-excel-with-anki/blob/master/screenshot/excel%20format.png

**Comment by BlueGreenMagick** [comment]
If you have any other questions, don't hesitate to ask! This addon has a very steep learning curve before it becomes usable, because it was written for only my personal use in mind.
