### ISSUE TITLE
Excel ->ANKI Error

### ISSUE THREAD

**Issue by pavlinbl4** [BlueGreenMagick/sync-excel-with-anki#21]
I get file from ANKI ( ANKI -> Tools -> (ANKI->Excel)  edited the file and run ( ANKI -> Tools -> (Excel ->ANKI))
and ERROR
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-11-05 09:37:48
Add-ons possibly involved: ⁨Anki Excel Sync⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "aqt.sync", line 117, in on_future_done
  File "aqt.main", line 970, in on_collection_sync_finished
  File "aqt.main", line 596, in after_sync
  File "aqt.mediasync", line 125, in show_diag_until_finished
  File "aqt.main", line 593, in after_media_sync
  File "/Users/evgeniy/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 253, in on_unload
    syncfunc()
  File "/Users/evgeniy/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 425, in _e2a_sync
    raise e
  File "/Users/evgeniy/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 334, in _e2a_sync
    raise DeckNameDoesNotExistError(decknm)
  File "/Users/evgeniy/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/errors.py", line 149, in __init__
    super.__init__()
TypeError: descriptor '__init__' of 'super' object needs an argument

**Comment by BlueGreenMagick** [comment]
Go to the add-on config and check if the deck name of `new-deck` exists

**Comment by pavlinbl4** [comment]
Thanks. Deck name of new-deck exists. `{
    "_directory": "/Volumes/big4photo/Documents/ANKI",
    "autosync_on_close": false,
    "autosync_on_launch": false,
    "col-width": [
        6,
        40,
        40,
        40,
        40
    ],
    "new-deck": "ANKI_excel"
}`
I  changed it from "Default" to different types. I used and tag name as new-desk name too. But this didn't help.

**Comment by BlueGreenMagick** [comment]
Can you try copy pasting the deck name into the config, to be sure it's completely identical? (From the deck overview list)

The error happens when the deck name in `new-deck` does not exist in your collection. And it has to be absolutely identical. (i.e. case sensitive)

**Comment by pavlinbl4** [comment]
Hello. Thank you. I copy deck name and use it as tag, as "new-deck" name  and name of empty folder in working directory. And  there was no mistakes. All worked good. Then I use another deck and used its name as a tag again, but  I didn't changed something in config file. And add-on worked again fine.
PS It's important to have a deck with same name with "new-deck" in config file to avoid mistakes. This deck may be empty.
