### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by gerardsonone** [BlueGreenMagick/sync-excel-with-anki#26]
After installing the plugin (windows11 64bits) and closing Anki, it does not open when I try to do so, but instead stays running in the background.
If I finish from the task manager and try to open Anki again, it opens and tells me that the add-on could not be installed.

Copy Debug:

Anki 24.04.1 (ccd9ca1a)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22621

When loading Anki Excel Sync:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\gerar\AppData\Roaming\Anki2\addons21\1832015432\__init__.py", line 6, in <module>
    from . import ankiExcelSync
  File "C:\Users\gerar\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\__init__.py", line 1, in <module>
    from .menu import modify_menu
  File "C:\Users\gerar\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\menu.py", line 1, in <module>
    from PyQt5.QtWidgets import QAction
ModuleNotFoundError: No module named 'PyQt5'

**Comment by BlueGreenMagick** [comment]
Sorry, but the add-on is no longer maintained anymore, and does not support newer versions of Anki. 

I'm not sure which version of Anki the add-on supports up to. You may have better luck using qt5 version of Anki though.

**Comment by finia2NA** [comment]
Fixed as of #28 👍
