### ISSUE TITLE
The Add-on is not compatible with the most updated anki version, thank you for your time.

### ISSUE THREAD

**Issue by SalmaBasiony** [BlueGreenMagick/sync-excel-with-anki#27]
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

When loading Anki Excel Sync:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1832015432\__init__.py", line 6, in <module>
    from . import ankiExcelSync
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\__init__.py", line 1, in <module>
    from .menu import modify_menu
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\menu.py", line 1, in <module>
    from PyQt5.QtWidgets import QAction
ModuleNotFoundError: No module named 'PyQt5'

**Comment by BlueGreenMagick** [comment]
Sorry, I'm no longer maintaining this add-on. If you really need to use it, you can download an older version of Anki.

alternatively, if you have knowledge in Python, you are free to fork the project - it will probably need minor changes to make it work with newer Anki versions.

**Comment by GPArchitect** [comment]
Salma, if you go to the addin page at https://ankiweb.net/shared/info/1832015432, there is a post there which begins with "I love this plugin and it works quite well. I did notice it stopped working if you update to the Qt6 version of anki..." That post has instructions which got it working for me. It's just one edit to the code to import QActions.

**Comment by finia2NA** [comment]
Fixed for QT6 as of #28
