### ISSUE TITLE
Exception: invalidSearch

### ISSUE THREAD

**Issue by freispiel** [BlueGreenMagick/sync-excel-with-anki#3]
Hi there,

This add-on sounds so nice, but no matter what deck I am trying to export from Anki, all I get is "Exception: invalidSearch".
Am I doing something wrong?

```
Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-02-16 11:29:17

Caught exception:
Traceback (most recent call last):
  File "C:\Users\********\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\menu.py", line 41, in confirm_a2e_sync
    ExcelSync().a2e_sync()
  File "C:\Users\********\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 249, in a2e_sync
    self.backup_then_sync(self._a2e_sync)
  File "C:\Users\********\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 243, in backup_then_sync
    mw.unloadCollection(on_unload)
  File "aqt\main.py", line 477, in unloadCollection
  File "aqt\main.py", line 751, in closeAllWindows
  File "aqt\__init__.py", line 105, in closeAll
  File "aqt\main.py", line 475, in callback
  File "C:\Users\********\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 242, in on_unload
    syncfunc()
  File "C:\Users\********\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 557, in _a2e_sync
    raise e
  File "C:\Users\********\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 446, in _a2e_sync
    card_ids = mw.col.findCards("tag:" + tag + "::*")
  File "lib\site-packages\anki\collection.py", line 618, in findCards
  File "lib\site-packages\anki\find.py", line 50, in findCards
Exception: invalidSearch
```

**Comment by BlueGreenMagick** [comment]
The addon is (hierarchical) tag based, not deck based.

In the directory you set up, create a folder with name of your tag. (of notes you want to export) You shouldn't have other folders in there.

If you want to export a deck, tag all the notes in the deck with a same tag before.

**Comment by freispiel** [comment]
My mistake, sorry: I thought deck and subdeck names were tags, too.
Maybe you could consider a slightly more explicit error message for the case "a tag that matches the directory name needs to be assigned"?

Again, my apologies!

**Comment by BlueGreenMagick** [comment]
Good to know it works! And sure that sounds good. I'll add that in the next update.
