### ISSUE TITLE
Initial Anki > Excel error

### ISSUE THREAD

**Issue by ghost** [BlueGreenMagick/sync-excel-with-anki#6]
Hi, been trying to set the sync up for the first time but when I try Anki > Excel I get the following error message, am I doing something wrong?

Debug info:
Anki 2.1.25 (898801eb) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-08 09:50:45

Caught exception:
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\menu.py", line 41, in confirm_a2e_sync
    ExcelSync().a2e_sync()
  File "C:\Users\andre\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 249, in a2e_sync
    self.backup_then_sync(self._a2e_sync)
  File "C:\Users\andre\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 243, in backup_then_sync
    mw.unloadCollection(on_unload)
  File "aqt\main.py", line 519, in unloadCollection
  File "aqt\main.py", line 783, in closeAllWindows
  File "aqt\__init__.py", line 107, in closeAll
  File "aqt\main.py", line 517, in callback
  File "C:\Users\andre\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 242, in on_unload
    syncfunc()
  File "C:\Users\andre\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 557, in _a2e_sync
    raise e
  File "C:\Users\andre\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 447, in _a2e_sync
    card_ids += mw.col.findCards("tag:" + tag)
TypeError: unsupported operand type(s) for +=: 'RepeatedScalarFieldContainer' and 'RepeatedScalarFieldContainer'

**Comment by BlueGreenMagick** [comment]
Thanks for bringing this to my notice! I investigated the issue, and found that the error seems to be because of a code change in Anki which was introduced in v2.1.25. While I will try to fix the issue sometime later, you would have to downgrade Anki to use the addon currently.

**Comment by BlueGreenMagick** [comment]
This issue should have been fixed in v1.2+.
