### ISSUE TITLE
Error syncing large deck

### ISSUE THREAD

**Issue by Blair291** [BlueGreenMagick/sync-excel-with-anki#7]
Hello - I have successfully been using your addon without a problem on a small deck, and it's been very useful. I recently tried to sync with one of my larger decks (about 2575 notes) and am receiving the below error. Can you please help? Thanks!

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-20 18:55:14
Add-ons possibly involved: Anki Excel Sync

Caught exception:
Traceback (most recent call last):
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 507, in _a2e_sync
    ef.write(notes[tag], models, col_width)
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/excel.py", line 145, in write
    ws.cell(row=crow, column=n+2).value = str(val_row[n])
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/openpyxl/cell/cell.py", line 252, in value
    self._bind_value(value)
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/openpyxl/cell/cell.py", line 205, in _bind_value
    value = self.check_string(value)
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/openpyxl/cell/cell.py", line 169, in check_string
    raise IllegalCharacterError
openpyxl.utils.exceptions.IllegalCharacterError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/menu.py", line 41, in confirm_a2e_sync
    ExcelSync().a2e_sync()
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 249, in a2e_sync
    self.backup_then_sync(self._a2e_sync)
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 243, in backup_then_sync
    mw.unloadCollection(on_unload)
  File "aqt/main.py", line 477, in unloadCollection
  File "aqt/main.py", line 751, in closeAllWindows
  File "aqt/__init__.py", line 105, in closeAll
  File "aqt/main.py", line 475, in callback
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 242, in on_unload
    syncfunc()
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 557, in _a2e_sync
    raise e
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 513, in _a2e_sync
    raise Exception("Error occured while creating excel file. \n%s"%str(e))
Exception: Error occured while creating excel file.

**Comment by BlueGreenMagick** [comment]
From what I understand of it, one of your note seems to have some kind of a special character that Excel won't accept. The latest update should now tell you which note causes the error. Could you try the update and post the result here? (Or if you managed to fix it yourself, how to do so?)

**Comment by Blair291** [comment]
Hi - I just updated the add-on and below is the new error message. I will try to look into the specific cards that have an error and will try to fix them. Thanks. 

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-25 17:15:17
Add-ons possibly involved: Anki Excel Sync

Error in sys.excepthook:
Traceback (most recent call last):
  File "aqt/errors.py", line 17, in excepthook
  File "aqt/errors.py", line 46, in write
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2580-2585: ordinal not in range(128)

Original exception was:
Traceback (most recent call last):
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/excel.py", line 161, in write
    ws.cell(row=crow, column=n + 2).value = str(val_row[n])
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/openpyxl/cell/cell.py", line 252, in value
    self._bind_value(value)
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/openpyxl/cell/cell.py", line 205, in _bind_value
    value = self.check_string(value)
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/openpyxl/cell/cell.py", line 169, in check_string
    raise IllegalCharacterError
openpyxl.utils.exceptions.IllegalCharacterError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 583, in _a2e_sync
    ef.write(notes[tag], models, col_width)
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/excel.py", line 165, in write
    e.message += """
AttributeError: 'IllegalCharacterError' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/menu.py", line 45, in confirm_a2e_sync
    ExcelSync().a2e_sync()
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 281, in a2e_sync
    self.backup_then_sync(self._a2e_sync)
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 275, in backup_then_sync
    mw.unloadCollection(on_unload)
  File "aqt/main.py", line 477, in unloadCollection
  File "aqt/main.py", line 751, in closeAllWindows
  File "aqt/__init__.py", line 105, in closeAll
  File "aqt/main.py", line 475, in callback
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 273, in on_unload
    syncfunc()
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 641, in _a2e_sync
    raise e
  File "/Users/blairplett/Library/Application Support/Anki2/addons21/1832015432/ankiExcelSync/sync.py", line 590, in _a2e_sync
    raise Exception(
Exception:

**Comment by Blair291** [comment]
Anyway you can tell me the specific note(s) that have an error?

**Comment by Blair291** [comment]
I was able to find the card that was causing the error. Once I deleted the corrupted card, the add-on worked perfectly. Thanks again for making the app.

**Comment by BlueGreenMagick** [comment]
Great that you found the problematic note! 

Regarding the error message, I meant to print out the note content, but it seems that it is not possible to print the characters in error messages as well. I'll have to make it print out note id instead. Reopening this issue since that should be fixed.
