### ISSUE TITLE
Error syncing Excel -> Anki

### ISSUE THREAD

**Issue by ghost** [BlueGreenMagick/sync-excel-with-anki#9]
Hi, 

I got the below error message when sycing my Excel file with Anki. The Excel file had previously be generated using Anki -> Excel

Thanks,
Andy

Debug info:
Anki 2.1.25 (898801eb) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-24 15:36:41

Caught exception:
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\menu.py", line 34, in confirm_e2a_sync
    ExcelSync().e2a_sync()
  File "C:\Users\andre\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 278, in e2a_sync
    self.backup_then_sync(self._e2a_sync)
  File "C:\Users\andre\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 275, in backup_then_sync
    mw.unloadCollection(on_unload)
  File "aqt\main.py", line 519, in unloadCollection
  File "aqt\main.py", line 783, in closeAllWindows
  File "aqt\__init__.py", line 107, in closeAll
  File "aqt\main.py", line 517, in callback
  File "C:\Users\andre\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 273, in on_unload
    syncfunc()
  File "C:\Users\andre\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 483, in _e2a_sync
    raise e
  File "C:\Users\andre\AppData\Roaming\Anki2\addons21\1832015432\ankiExcelSync\sync.py", line 412, in _e2a_sync
    mw.progress.start("Excel -> Anki Sync")
  File "aqt\progress.py", line 70, in start
TypeError: setMaximum(self, int): argument 1 has unexpected type 'str'

**Comment by BlueGreenMagick** [comment]
Thanks for the bug report. It should be fixed in the latest update.
